// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Milestone is the predicate function for milestone builders.
type Milestone func(*sql.Selector)

// Project is the predicate function for project builders.
type Project func(*sql.Selector)

// Task is the predicate function for task builders.
type Task func(*sql.Selector)

// Worklog is the predicate function for worklog builders.
type Worklog func(*sql.Selector)
