// Code generated by ent, DO NOT EDIT.

package worklog

import (
	"project-manager/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Worklog {
	return predicate.Worklog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Worklog {
	return predicate.Worklog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Worklog {
	return predicate.Worklog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Worklog {
	return predicate.Worklog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Worklog {
	return predicate.Worklog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Worklog {
	return predicate.Worklog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Worklog {
	return predicate.Worklog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Worklog {
	return predicate.Worklog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Worklog {
	return predicate.Worklog(sql.FieldLTE(FieldID, id))
}

// UserName applies equality check predicate on the "user_name" field. It's identical to UserNameEQ.
func UserName(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldEQ(FieldUserName, v))
}

// Hours applies equality check predicate on the "hours" field. It's identical to HoursEQ.
func Hours(v float64) predicate.Worklog {
	return predicate.Worklog(sql.FieldEQ(FieldHours, v))
}

// WorkDate applies equality check predicate on the "work_date" field. It's identical to WorkDateEQ.
func WorkDate(v time.Time) predicate.Worklog {
	return predicate.Worklog(sql.FieldEQ(FieldWorkDate, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldEQ(FieldDescription, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Worklog {
	return predicate.Worklog(sql.FieldEQ(FieldCreatedAt, v))
}

// UserNameEQ applies the EQ predicate on the "user_name" field.
func UserNameEQ(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldEQ(FieldUserName, v))
}

// UserNameNEQ applies the NEQ predicate on the "user_name" field.
func UserNameNEQ(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldNEQ(FieldUserName, v))
}

// UserNameIn applies the In predicate on the "user_name" field.
func UserNameIn(vs ...string) predicate.Worklog {
	return predicate.Worklog(sql.FieldIn(FieldUserName, vs...))
}

// UserNameNotIn applies the NotIn predicate on the "user_name" field.
func UserNameNotIn(vs ...string) predicate.Worklog {
	return predicate.Worklog(sql.FieldNotIn(FieldUserName, vs...))
}

// UserNameGT applies the GT predicate on the "user_name" field.
func UserNameGT(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldGT(FieldUserName, v))
}

// UserNameGTE applies the GTE predicate on the "user_name" field.
func UserNameGTE(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldGTE(FieldUserName, v))
}

// UserNameLT applies the LT predicate on the "user_name" field.
func UserNameLT(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldLT(FieldUserName, v))
}

// UserNameLTE applies the LTE predicate on the "user_name" field.
func UserNameLTE(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldLTE(FieldUserName, v))
}

// UserNameContains applies the Contains predicate on the "user_name" field.
func UserNameContains(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldContains(FieldUserName, v))
}

// UserNameHasPrefix applies the HasPrefix predicate on the "user_name" field.
func UserNameHasPrefix(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldHasPrefix(FieldUserName, v))
}

// UserNameHasSuffix applies the HasSuffix predicate on the "user_name" field.
func UserNameHasSuffix(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldHasSuffix(FieldUserName, v))
}

// UserNameEqualFold applies the EqualFold predicate on the "user_name" field.
func UserNameEqualFold(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldEqualFold(FieldUserName, v))
}

// UserNameContainsFold applies the ContainsFold predicate on the "user_name" field.
func UserNameContainsFold(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldContainsFold(FieldUserName, v))
}

// HoursEQ applies the EQ predicate on the "hours" field.
func HoursEQ(v float64) predicate.Worklog {
	return predicate.Worklog(sql.FieldEQ(FieldHours, v))
}

// HoursNEQ applies the NEQ predicate on the "hours" field.
func HoursNEQ(v float64) predicate.Worklog {
	return predicate.Worklog(sql.FieldNEQ(FieldHours, v))
}

// HoursIn applies the In predicate on the "hours" field.
func HoursIn(vs ...float64) predicate.Worklog {
	return predicate.Worklog(sql.FieldIn(FieldHours, vs...))
}

// HoursNotIn applies the NotIn predicate on the "hours" field.
func HoursNotIn(vs ...float64) predicate.Worklog {
	return predicate.Worklog(sql.FieldNotIn(FieldHours, vs...))
}

// HoursGT applies the GT predicate on the "hours" field.
func HoursGT(v float64) predicate.Worklog {
	return predicate.Worklog(sql.FieldGT(FieldHours, v))
}

// HoursGTE applies the GTE predicate on the "hours" field.
func HoursGTE(v float64) predicate.Worklog {
	return predicate.Worklog(sql.FieldGTE(FieldHours, v))
}

// HoursLT applies the LT predicate on the "hours" field.
func HoursLT(v float64) predicate.Worklog {
	return predicate.Worklog(sql.FieldLT(FieldHours, v))
}

// HoursLTE applies the LTE predicate on the "hours" field.
func HoursLTE(v float64) predicate.Worklog {
	return predicate.Worklog(sql.FieldLTE(FieldHours, v))
}

// WorkDateEQ applies the EQ predicate on the "work_date" field.
func WorkDateEQ(v time.Time) predicate.Worklog {
	return predicate.Worklog(sql.FieldEQ(FieldWorkDate, v))
}

// WorkDateNEQ applies the NEQ predicate on the "work_date" field.
func WorkDateNEQ(v time.Time) predicate.Worklog {
	return predicate.Worklog(sql.FieldNEQ(FieldWorkDate, v))
}

// WorkDateIn applies the In predicate on the "work_date" field.
func WorkDateIn(vs ...time.Time) predicate.Worklog {
	return predicate.Worklog(sql.FieldIn(FieldWorkDate, vs...))
}

// WorkDateNotIn applies the NotIn predicate on the "work_date" field.
func WorkDateNotIn(vs ...time.Time) predicate.Worklog {
	return predicate.Worklog(sql.FieldNotIn(FieldWorkDate, vs...))
}

// WorkDateGT applies the GT predicate on the "work_date" field.
func WorkDateGT(v time.Time) predicate.Worklog {
	return predicate.Worklog(sql.FieldGT(FieldWorkDate, v))
}

// WorkDateGTE applies the GTE predicate on the "work_date" field.
func WorkDateGTE(v time.Time) predicate.Worklog {
	return predicate.Worklog(sql.FieldGTE(FieldWorkDate, v))
}

// WorkDateLT applies the LT predicate on the "work_date" field.
func WorkDateLT(v time.Time) predicate.Worklog {
	return predicate.Worklog(sql.FieldLT(FieldWorkDate, v))
}

// WorkDateLTE applies the LTE predicate on the "work_date" field.
func WorkDateLTE(v time.Time) predicate.Worklog {
	return predicate.Worklog(sql.FieldLTE(FieldWorkDate, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Worklog {
	return predicate.Worklog(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Worklog {
	return predicate.Worklog(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Worklog {
	return predicate.Worklog(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Worklog {
	return predicate.Worklog(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldContainsFold(FieldDescription, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Worklog {
	return predicate.Worklog(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Worklog {
	return predicate.Worklog(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Worklog {
	return predicate.Worklog(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Worklog {
	return predicate.Worklog(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Worklog {
	return predicate.Worklog(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Worklog {
	return predicate.Worklog(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Worklog {
	return predicate.Worklog(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Worklog {
	return predicate.Worklog(sql.FieldLTE(FieldCreatedAt, v))
}

// HasTask applies the HasEdge predicate on the "task" edge.
func HasTask() predicate.Worklog {
	return predicate.Worklog(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TaskTable, TaskColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTaskWith applies the HasEdge predicate on the "task" edge with a given conditions (other predicates).
func HasTaskWith(preds ...predicate.Task) predicate.Worklog {
	return predicate.Worklog(func(s *sql.Selector) {
		step := newTaskStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Worklog) predicate.Worklog {
	return predicate.Worklog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Worklog) predicate.Worklog {
	return predicate.Worklog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Worklog) predicate.Worklog {
	return predicate.Worklog(sql.NotPredicates(p))
}
