// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"project-manager/ent/milestone"
	"project-manager/ent/project"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Milestone is the model entity for the Milestone schema.
type Milestone struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// DueDate holds the value of the "due_date" field.
	DueDate *time.Time `json:"due_date,omitempty"`
	// Status holds the value of the "status" field.
	Status milestone.Status `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MilestoneQuery when eager-loading is set.
	Edges              MilestoneEdges `json:"edges"`
	project_milestones *uuid.UUID
	selectValues       sql.SelectValues
}

// MilestoneEdges holds the relations/edges for other nodes in the graph.
type MilestoneEdges struct {
	// Project holds the value of the project edge.
	Project *Project `json:"project,omitempty"`
	// Tasks holds the value of the tasks edge.
	Tasks []*Task `json:"tasks,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ProjectOrErr returns the Project value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MilestoneEdges) ProjectOrErr() (*Project, error) {
	if e.Project != nil {
		return e.Project, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: project.Label}
	}
	return nil, &NotLoadedError{edge: "project"}
}

// TasksOrErr returns the Tasks value or an error if the edge
// was not loaded in eager-loading.
func (e MilestoneEdges) TasksOrErr() ([]*Task, error) {
	if e.loadedTypes[1] {
		return e.Tasks, nil
	}
	return nil, &NotLoadedError{edge: "tasks"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Milestone) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case milestone.FieldName, milestone.FieldStatus:
			values[i] = new(sql.NullString)
		case milestone.FieldDueDate, milestone.FieldCreatedAt, milestone.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case milestone.FieldID:
			values[i] = new(uuid.UUID)
		case milestone.ForeignKeys[0]: // project_milestones
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Milestone fields.
func (_m *Milestone) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case milestone.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case milestone.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case milestone.FieldDueDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field due_date", values[i])
			} else if value.Valid {
				_m.DueDate = new(time.Time)
				*_m.DueDate = value.Time
			}
		case milestone.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = milestone.Status(value.String)
			}
		case milestone.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case milestone.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case milestone.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field project_milestones", values[i])
			} else if value.Valid {
				_m.project_milestones = new(uuid.UUID)
				*_m.project_milestones = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Milestone.
// This includes values selected through modifiers, order, etc.
func (_m *Milestone) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProject queries the "project" edge of the Milestone entity.
func (_m *Milestone) QueryProject() *ProjectQuery {
	return NewMilestoneClient(_m.config).QueryProject(_m)
}

// QueryTasks queries the "tasks" edge of the Milestone entity.
func (_m *Milestone) QueryTasks() *TaskQuery {
	return NewMilestoneClient(_m.config).QueryTasks(_m)
}

// Update returns a builder for updating this Milestone.
// Note that you need to call Milestone.Unwrap() before calling this method if this Milestone
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Milestone) Update() *MilestoneUpdateOne {
	return NewMilestoneClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Milestone entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Milestone) Unwrap() *Milestone {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Milestone is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Milestone) String() string {
	var builder strings.Builder
	builder.WriteString("Milestone(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	if v := _m.DueDate; v != nil {
		builder.WriteString("due_date=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Milestones is a parsable slice of Milestone.
type Milestones []*Milestone
