// Code generated by ent, DO NOT EDIT.

package ent

import (
	"project-manager/ent/milestone"
	"project-manager/ent/project"
	"project-manager/ent/schema"
	"project-manager/ent/task"
	"project-manager/ent/worklog"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	milestoneFields := schema.Milestone{}.Fields()
	_ = milestoneFields
	// milestoneDescName is the schema descriptor for name field.
	milestoneDescName := milestoneFields[1].Descriptor()
	// milestone.NameValidator is a validator for the "name" field. It is called by the builders before save.
	milestone.NameValidator = func() func(string) error {
		validators := milestoneDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// milestoneDescCreatedAt is the schema descriptor for created_at field.
	milestoneDescCreatedAt := milestoneFields[4].Descriptor()
	// milestone.DefaultCreatedAt holds the default value on creation for the created_at field.
	milestone.DefaultCreatedAt = milestoneDescCreatedAt.Default.(func() time.Time)
	// milestoneDescUpdatedAt is the schema descriptor for updated_at field.
	milestoneDescUpdatedAt := milestoneFields[5].Descriptor()
	// milestone.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	milestone.DefaultUpdatedAt = milestoneDescUpdatedAt.Default.(func() time.Time)
	// milestone.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	milestone.UpdateDefaultUpdatedAt = milestoneDescUpdatedAt.UpdateDefault.(func() time.Time)
	// milestoneDescID is the schema descriptor for id field.
	milestoneDescID := milestoneFields[0].Descriptor()
	// milestone.DefaultID holds the default value on creation for the id field.
	milestone.DefaultID = milestoneDescID.Default.(func() uuid.UUID)
	projectFields := schema.Project{}.Fields()
	_ = projectFields
	// projectDescName is the schema descriptor for name field.
	projectDescName := projectFields[1].Descriptor()
	// project.NameValidator is a validator for the "name" field. It is called by the builders before save.
	project.NameValidator = func() func(string) error {
		validators := projectDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// projectDescCreatedAt is the schema descriptor for created_at field.
	projectDescCreatedAt := projectFields[6].Descriptor()
	// project.DefaultCreatedAt holds the default value on creation for the created_at field.
	project.DefaultCreatedAt = projectDescCreatedAt.Default.(func() time.Time)
	// projectDescUpdatedAt is the schema descriptor for updated_at field.
	projectDescUpdatedAt := projectFields[7].Descriptor()
	// project.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	project.DefaultUpdatedAt = projectDescUpdatedAt.Default.(func() time.Time)
	// project.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	project.UpdateDefaultUpdatedAt = projectDescUpdatedAt.UpdateDefault.(func() time.Time)
	// projectDescID is the schema descriptor for id field.
	projectDescID := projectFields[0].Descriptor()
	// project.DefaultID holds the default value on creation for the id field.
	project.DefaultID = projectDescID.Default.(func() uuid.UUID)
	taskFields := schema.Task{}.Fields()
	_ = taskFields
	// taskDescWbsCode is the schema descriptor for wbs_code field.
	taskDescWbsCode := taskFields[1].Descriptor()
	// task.WbsCodeValidator is a validator for the "wbs_code" field. It is called by the builders before save.
	task.WbsCodeValidator = taskDescWbsCode.Validators[0].(func(string) error)
	// taskDescName is the schema descriptor for name field.
	taskDescName := taskFields[2].Descriptor()
	// task.NameValidator is a validator for the "name" field. It is called by the builders before save.
	task.NameValidator = func() func(string) error {
		validators := taskDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// taskDescAssignee is the schema descriptor for assignee field.
	taskDescAssignee := taskFields[6].Descriptor()
	// task.AssigneeValidator is a validator for the "assignee" field. It is called by the builders before save.
	task.AssigneeValidator = taskDescAssignee.Validators[0].(func(string) error)
	// taskDescSortOrder is the schema descriptor for sort_order field.
	taskDescSortOrder := taskFields[11].Descriptor()
	// task.DefaultSortOrder holds the default value on creation for the sort_order field.
	task.DefaultSortOrder = taskDescSortOrder.Default.(int)
	// taskDescCreatedAt is the schema descriptor for created_at field.
	taskDescCreatedAt := taskFields[12].Descriptor()
	// task.DefaultCreatedAt holds the default value on creation for the created_at field.
	task.DefaultCreatedAt = taskDescCreatedAt.Default.(func() time.Time)
	// taskDescUpdatedAt is the schema descriptor for updated_at field.
	taskDescUpdatedAt := taskFields[13].Descriptor()
	// task.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	task.DefaultUpdatedAt = taskDescUpdatedAt.Default.(func() time.Time)
	// task.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	task.UpdateDefaultUpdatedAt = taskDescUpdatedAt.UpdateDefault.(func() time.Time)
	// taskDescID is the schema descriptor for id field.
	taskDescID := taskFields[0].Descriptor()
	// task.DefaultID holds the default value on creation for the id field.
	task.DefaultID = taskDescID.Default.(func() uuid.UUID)
	worklogFields := schema.Worklog{}.Fields()
	_ = worklogFields
	// worklogDescUserName is the schema descriptor for user_name field.
	worklogDescUserName := worklogFields[1].Descriptor()
	// worklog.UserNameValidator is a validator for the "user_name" field. It is called by the builders before save.
	worklog.UserNameValidator = func() func(string) error {
		validators := worklogDescUserName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(user_name string) error {
			for _, fn := range fns {
				if err := fn(user_name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// worklogDescCreatedAt is the schema descriptor for created_at field.
	worklogDescCreatedAt := worklogFields[5].Descriptor()
	// worklog.DefaultCreatedAt holds the default value on creation for the created_at field.
	worklog.DefaultCreatedAt = worklogDescCreatedAt.Default.(func() time.Time)
	// worklogDescID is the schema descriptor for id field.
	worklogDescID := worklogFields[0].Descriptor()
	// worklog.DefaultID holds the default value on creation for the id field.
	worklog.DefaultID = worklogDescID.Default.(func() uuid.UUID)
}
