// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"project-manager/ent/milestone"
	"project-manager/ent/predicate"
	"project-manager/ent/project"
	"project-manager/ent/task"
	"project-manager/ent/worklog"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// TaskUpdate is the builder for updating Task entities.
type TaskUpdate struct {
	config
	hooks    []Hook
	mutation *TaskMutation
}

// Where appends a list predicates to the TaskUpdate builder.
func (_u *TaskUpdate) Where(ps ...predicate.Task) *TaskUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetWbsCode sets the "wbs_code" field.
func (_u *TaskUpdate) SetWbsCode(v string) *TaskUpdate {
	_u.mutation.SetWbsCode(v)
	return _u
}

// SetNillableWbsCode sets the "wbs_code" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableWbsCode(v *string) *TaskUpdate {
	if v != nil {
		_u.SetWbsCode(*v)
	}
	return _u
}

// ClearWbsCode clears the value of the "wbs_code" field.
func (_u *TaskUpdate) ClearWbsCode() *TaskUpdate {
	_u.mutation.ClearWbsCode()
	return _u
}

// SetName sets the "name" field.
func (_u *TaskUpdate) SetName(v string) *TaskUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableName(v *string) *TaskUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *TaskUpdate) SetDescription(v string) *TaskUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableDescription(v *string) *TaskUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *TaskUpdate) ClearDescription() *TaskUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetStatus sets the "status" field.
func (_u *TaskUpdate) SetStatus(v task.Status) *TaskUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableStatus(v *task.Status) *TaskUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *TaskUpdate) SetPriority(v task.Priority) *TaskUpdate {
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *TaskUpdate) SetNillablePriority(v *task.Priority) *TaskUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// SetAssignee sets the "assignee" field.
func (_u *TaskUpdate) SetAssignee(v string) *TaskUpdate {
	_u.mutation.SetAssignee(v)
	return _u
}

// SetNillableAssignee sets the "assignee" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableAssignee(v *string) *TaskUpdate {
	if v != nil {
		_u.SetAssignee(*v)
	}
	return _u
}

// ClearAssignee clears the value of the "assignee" field.
func (_u *TaskUpdate) ClearAssignee() *TaskUpdate {
	_u.mutation.ClearAssignee()
	return _u
}

// SetEstimatedHours sets the "estimated_hours" field.
func (_u *TaskUpdate) SetEstimatedHours(v float64) *TaskUpdate {
	_u.mutation.ResetEstimatedHours()
	_u.mutation.SetEstimatedHours(v)
	return _u
}

// SetNillableEstimatedHours sets the "estimated_hours" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableEstimatedHours(v *float64) *TaskUpdate {
	if v != nil {
		_u.SetEstimatedHours(*v)
	}
	return _u
}

// AddEstimatedHours adds value to the "estimated_hours" field.
func (_u *TaskUpdate) AddEstimatedHours(v float64) *TaskUpdate {
	_u.mutation.AddEstimatedHours(v)
	return _u
}

// ClearEstimatedHours clears the value of the "estimated_hours" field.
func (_u *TaskUpdate) ClearEstimatedHours() *TaskUpdate {
	_u.mutation.ClearEstimatedHours()
	return _u
}

// SetActualHours sets the "actual_hours" field.
func (_u *TaskUpdate) SetActualHours(v float64) *TaskUpdate {
	_u.mutation.ResetActualHours()
	_u.mutation.SetActualHours(v)
	return _u
}

// SetNillableActualHours sets the "actual_hours" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableActualHours(v *float64) *TaskUpdate {
	if v != nil {
		_u.SetActualHours(*v)
	}
	return _u
}

// AddActualHours adds value to the "actual_hours" field.
func (_u *TaskUpdate) AddActualHours(v float64) *TaskUpdate {
	_u.mutation.AddActualHours(v)
	return _u
}

// ClearActualHours clears the value of the "actual_hours" field.
func (_u *TaskUpdate) ClearActualHours() *TaskUpdate {
	_u.mutation.ClearActualHours()
	return _u
}

// SetStartDate sets the "start_date" field.
func (_u *TaskUpdate) SetStartDate(v time.Time) *TaskUpdate {
	_u.mutation.SetStartDate(v)
	return _u
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableStartDate(v *time.Time) *TaskUpdate {
	if v != nil {
		_u.SetStartDate(*v)
	}
	return _u
}

// ClearStartDate clears the value of the "start_date" field.
func (_u *TaskUpdate) ClearStartDate() *TaskUpdate {
	_u.mutation.ClearStartDate()
	return _u
}

// SetEndDate sets the "end_date" field.
func (_u *TaskUpdate) SetEndDate(v time.Time) *TaskUpdate {
	_u.mutation.SetEndDate(v)
	return _u
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableEndDate(v *time.Time) *TaskUpdate {
	if v != nil {
		_u.SetEndDate(*v)
	}
	return _u
}

// ClearEndDate clears the value of the "end_date" field.
func (_u *TaskUpdate) ClearEndDate() *TaskUpdate {
	_u.mutation.ClearEndDate()
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *TaskUpdate) SetSortOrder(v int) *TaskUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableSortOrder(v *int) *TaskUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *TaskUpdate) AddSortOrder(v int) *TaskUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TaskUpdate) SetUpdatedAt(v time.Time) *TaskUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetProjectID sets the "project" edge to the Project entity by ID.
func (_u *TaskUpdate) SetProjectID(id uuid.UUID) *TaskUpdate {
	_u.mutation.SetProjectID(id)
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *TaskUpdate) SetProject(v *Project) *TaskUpdate {
	return _u.SetProjectID(v.ID)
}

// SetMilestoneID sets the "milestone" edge to the Milestone entity by ID.
func (_u *TaskUpdate) SetMilestoneID(id uuid.UUID) *TaskUpdate {
	_u.mutation.SetMilestoneID(id)
	return _u
}

// SetNillableMilestoneID sets the "milestone" edge to the Milestone entity by ID if the given value is not nil.
func (_u *TaskUpdate) SetNillableMilestoneID(id *uuid.UUID) *TaskUpdate {
	if id != nil {
		_u = _u.SetMilestoneID(*id)
	}
	return _u
}

// SetMilestone sets the "milestone" edge to the Milestone entity.
func (_u *TaskUpdate) SetMilestone(v *Milestone) *TaskUpdate {
	return _u.SetMilestoneID(v.ID)
}

// SetParentID sets the "parent" edge to the Task entity by ID.
func (_u *TaskUpdate) SetParentID(id uuid.UUID) *TaskUpdate {
	_u.mutation.SetParentID(id)
	return _u
}

// SetNillableParentID sets the "parent" edge to the Task entity by ID if the given value is not nil.
func (_u *TaskUpdate) SetNillableParentID(id *uuid.UUID) *TaskUpdate {
	if id != nil {
		_u = _u.SetParentID(*id)
	}
	return _u
}

// SetParent sets the "parent" edge to the Task entity.
func (_u *TaskUpdate) SetParent(v *Task) *TaskUpdate {
	return _u.SetParentID(v.ID)
}

// AddChildIDs adds the "children" edge to the Task entity by IDs.
func (_u *TaskUpdate) AddChildIDs(ids ...uuid.UUID) *TaskUpdate {
	_u.mutation.AddChildIDs(ids...)
	return _u
}

// AddChildren adds the "children" edges to the Task entity.
func (_u *TaskUpdate) AddChildren(v ...*Task) *TaskUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChildIDs(ids...)
}

// AddWorklogIDs adds the "worklogs" edge to the Worklog entity by IDs.
func (_u *TaskUpdate) AddWorklogIDs(ids ...uuid.UUID) *TaskUpdate {
	_u.mutation.AddWorklogIDs(ids...)
	return _u
}

// AddWorklogs adds the "worklogs" edges to the Worklog entity.
func (_u *TaskUpdate) AddWorklogs(v ...*Worklog) *TaskUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddWorklogIDs(ids...)
}

// Mutation returns the TaskMutation object of the builder.
func (_u *TaskUpdate) Mutation() *TaskMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *TaskUpdate) ClearProject() *TaskUpdate {
	_u.mutation.ClearProject()
	return _u
}

// ClearMilestone clears the "milestone" edge to the Milestone entity.
func (_u *TaskUpdate) ClearMilestone() *TaskUpdate {
	_u.mutation.ClearMilestone()
	return _u
}

// ClearParent clears the "parent" edge to the Task entity.
func (_u *TaskUpdate) ClearParent() *TaskUpdate {
	_u.mutation.ClearParent()
	return _u
}

// ClearChildren clears all "children" edges to the Task entity.
func (_u *TaskUpdate) ClearChildren() *TaskUpdate {
	_u.mutation.ClearChildren()
	return _u
}

// RemoveChildIDs removes the "children" edge to Task entities by IDs.
func (_u *TaskUpdate) RemoveChildIDs(ids ...uuid.UUID) *TaskUpdate {
	_u.mutation.RemoveChildIDs(ids...)
	return _u
}

// RemoveChildren removes "children" edges to Task entities.
func (_u *TaskUpdate) RemoveChildren(v ...*Task) *TaskUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChildIDs(ids...)
}

// ClearWorklogs clears all "worklogs" edges to the Worklog entity.
func (_u *TaskUpdate) ClearWorklogs() *TaskUpdate {
	_u.mutation.ClearWorklogs()
	return _u
}

// RemoveWorklogIDs removes the "worklogs" edge to Worklog entities by IDs.
func (_u *TaskUpdate) RemoveWorklogIDs(ids ...uuid.UUID) *TaskUpdate {
	_u.mutation.RemoveWorklogIDs(ids...)
	return _u
}

// RemoveWorklogs removes "worklogs" edges to Worklog entities.
func (_u *TaskUpdate) RemoveWorklogs(v ...*Worklog) *TaskUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveWorklogIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TaskUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TaskUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TaskUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TaskUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TaskUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := task.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TaskUpdate) check() error {
	if v, ok := _u.mutation.WbsCode(); ok {
		if err := task.WbsCodeValidator(v); err != nil {
			return &ValidationError{Name: "wbs_code", err: fmt.Errorf(`ent: validator failed for field "Task.wbs_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := task.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Task.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := task.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Task.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Priority(); ok {
		if err := task.PriorityValidator(v); err != nil {
			return &ValidationError{Name: "priority", err: fmt.Errorf(`ent: validator failed for field "Task.priority": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Assignee(); ok {
		if err := task.AssigneeValidator(v); err != nil {
			return &ValidationError{Name: "assignee", err: fmt.Errorf(`ent: validator failed for field "Task.assignee": %w`, err)}
		}
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Task.project"`)
	}
	return nil
}

func (_u *TaskUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(task.Table, task.Columns, sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.WbsCode(); ok {
		_spec.SetField(task.FieldWbsCode, field.TypeString, value)
	}
	if _u.mutation.WbsCodeCleared() {
		_spec.ClearField(task.FieldWbsCode, field.TypeString)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(task.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(task.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(task.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(task.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(task.FieldPriority, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Assignee(); ok {
		_spec.SetField(task.FieldAssignee, field.TypeString, value)
	}
	if _u.mutation.AssigneeCleared() {
		_spec.ClearField(task.FieldAssignee, field.TypeString)
	}
	if value, ok := _u.mutation.EstimatedHours(); ok {
		_spec.SetField(task.FieldEstimatedHours, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedEstimatedHours(); ok {
		_spec.AddField(task.FieldEstimatedHours, field.TypeFloat64, value)
	}
	if _u.mutation.EstimatedHoursCleared() {
		_spec.ClearField(task.FieldEstimatedHours, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ActualHours(); ok {
		_spec.SetField(task.FieldActualHours, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedActualHours(); ok {
		_spec.AddField(task.FieldActualHours, field.TypeFloat64, value)
	}
	if _u.mutation.ActualHoursCleared() {
		_spec.ClearField(task.FieldActualHours, field.TypeFloat64)
	}
	if value, ok := _u.mutation.StartDate(); ok {
		_spec.SetField(task.FieldStartDate, field.TypeTime, value)
	}
	if _u.mutation.StartDateCleared() {
		_spec.ClearField(task.FieldStartDate, field.TypeTime)
	}
	if value, ok := _u.mutation.EndDate(); ok {
		_spec.SetField(task.FieldEndDate, field.TypeTime, value)
	}
	if _u.mutation.EndDateCleared() {
		_spec.ClearField(task.FieldEndDate, field.TypeTime)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(task.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(task.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(task.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.ProjectTable,
			Columns: []string{task.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.ProjectTable,
			Columns: []string{task.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MilestoneCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.MilestoneTable,
			Columns: []string{task.MilestoneColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(milestone.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MilestoneIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.MilestoneTable,
			Columns: []string{task.MilestoneColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(milestone.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.ParentTable,
			Columns: []string{task.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.ParentTable,
			Columns: []string{task.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.ChildrenTable,
			Columns: []string{task.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !_u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.ChildrenTable,
			Columns: []string{task.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.ChildrenTable,
			Columns: []string{task.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.WorklogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.WorklogsTable,
			Columns: []string{task.WorklogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(worklog.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedWorklogsIDs(); len(nodes) > 0 && !_u.mutation.WorklogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.WorklogsTable,
			Columns: []string{task.WorklogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(worklog.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WorklogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.WorklogsTable,
			Columns: []string{task.WorklogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(worklog.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{task.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TaskUpdateOne is the builder for updating a single Task entity.
type TaskUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TaskMutation
}

// SetWbsCode sets the "wbs_code" field.
func (_u *TaskUpdateOne) SetWbsCode(v string) *TaskUpdateOne {
	_u.mutation.SetWbsCode(v)
	return _u
}

// SetNillableWbsCode sets the "wbs_code" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableWbsCode(v *string) *TaskUpdateOne {
	if v != nil {
		_u.SetWbsCode(*v)
	}
	return _u
}

// ClearWbsCode clears the value of the "wbs_code" field.
func (_u *TaskUpdateOne) ClearWbsCode() *TaskUpdateOne {
	_u.mutation.ClearWbsCode()
	return _u
}

// SetName sets the "name" field.
func (_u *TaskUpdateOne) SetName(v string) *TaskUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableName(v *string) *TaskUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *TaskUpdateOne) SetDescription(v string) *TaskUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableDescription(v *string) *TaskUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *TaskUpdateOne) ClearDescription() *TaskUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetStatus sets the "status" field.
func (_u *TaskUpdateOne) SetStatus(v task.Status) *TaskUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableStatus(v *task.Status) *TaskUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *TaskUpdateOne) SetPriority(v task.Priority) *TaskUpdateOne {
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillablePriority(v *task.Priority) *TaskUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// SetAssignee sets the "assignee" field.
func (_u *TaskUpdateOne) SetAssignee(v string) *TaskUpdateOne {
	_u.mutation.SetAssignee(v)
	return _u
}

// SetNillableAssignee sets the "assignee" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableAssignee(v *string) *TaskUpdateOne {
	if v != nil {
		_u.SetAssignee(*v)
	}
	return _u
}

// ClearAssignee clears the value of the "assignee" field.
func (_u *TaskUpdateOne) ClearAssignee() *TaskUpdateOne {
	_u.mutation.ClearAssignee()
	return _u
}

// SetEstimatedHours sets the "estimated_hours" field.
func (_u *TaskUpdateOne) SetEstimatedHours(v float64) *TaskUpdateOne {
	_u.mutation.ResetEstimatedHours()
	_u.mutation.SetEstimatedHours(v)
	return _u
}

// SetNillableEstimatedHours sets the "estimated_hours" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableEstimatedHours(v *float64) *TaskUpdateOne {
	if v != nil {
		_u.SetEstimatedHours(*v)
	}
	return _u
}

// AddEstimatedHours adds value to the "estimated_hours" field.
func (_u *TaskUpdateOne) AddEstimatedHours(v float64) *TaskUpdateOne {
	_u.mutation.AddEstimatedHours(v)
	return _u
}

// ClearEstimatedHours clears the value of the "estimated_hours" field.
func (_u *TaskUpdateOne) ClearEstimatedHours() *TaskUpdateOne {
	_u.mutation.ClearEstimatedHours()
	return _u
}

// SetActualHours sets the "actual_hours" field.
func (_u *TaskUpdateOne) SetActualHours(v float64) *TaskUpdateOne {
	_u.mutation.ResetActualHours()
	_u.mutation.SetActualHours(v)
	return _u
}

// SetNillableActualHours sets the "actual_hours" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableActualHours(v *float64) *TaskUpdateOne {
	if v != nil {
		_u.SetActualHours(*v)
	}
	return _u
}

// AddActualHours adds value to the "actual_hours" field.
func (_u *TaskUpdateOne) AddActualHours(v float64) *TaskUpdateOne {
	_u.mutation.AddActualHours(v)
	return _u
}

// ClearActualHours clears the value of the "actual_hours" field.
func (_u *TaskUpdateOne) ClearActualHours() *TaskUpdateOne {
	_u.mutation.ClearActualHours()
	return _u
}

// SetStartDate sets the "start_date" field.
func (_u *TaskUpdateOne) SetStartDate(v time.Time) *TaskUpdateOne {
	_u.mutation.SetStartDate(v)
	return _u
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableStartDate(v *time.Time) *TaskUpdateOne {
	if v != nil {
		_u.SetStartDate(*v)
	}
	return _u
}

// ClearStartDate clears the value of the "start_date" field.
func (_u *TaskUpdateOne) ClearStartDate() *TaskUpdateOne {
	_u.mutation.ClearStartDate()
	return _u
}

// SetEndDate sets the "end_date" field.
func (_u *TaskUpdateOne) SetEndDate(v time.Time) *TaskUpdateOne {
	_u.mutation.SetEndDate(v)
	return _u
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableEndDate(v *time.Time) *TaskUpdateOne {
	if v != nil {
		_u.SetEndDate(*v)
	}
	return _u
}

// ClearEndDate clears the value of the "end_date" field.
func (_u *TaskUpdateOne) ClearEndDate() *TaskUpdateOne {
	_u.mutation.ClearEndDate()
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *TaskUpdateOne) SetSortOrder(v int) *TaskUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableSortOrder(v *int) *TaskUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *TaskUpdateOne) AddSortOrder(v int) *TaskUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TaskUpdateOne) SetUpdatedAt(v time.Time) *TaskUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetProjectID sets the "project" edge to the Project entity by ID.
func (_u *TaskUpdateOne) SetProjectID(id uuid.UUID) *TaskUpdateOne {
	_u.mutation.SetProjectID(id)
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *TaskUpdateOne) SetProject(v *Project) *TaskUpdateOne {
	return _u.SetProjectID(v.ID)
}

// SetMilestoneID sets the "milestone" edge to the Milestone entity by ID.
func (_u *TaskUpdateOne) SetMilestoneID(id uuid.UUID) *TaskUpdateOne {
	_u.mutation.SetMilestoneID(id)
	return _u
}

// SetNillableMilestoneID sets the "milestone" edge to the Milestone entity by ID if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableMilestoneID(id *uuid.UUID) *TaskUpdateOne {
	if id != nil {
		_u = _u.SetMilestoneID(*id)
	}
	return _u
}

// SetMilestone sets the "milestone" edge to the Milestone entity.
func (_u *TaskUpdateOne) SetMilestone(v *Milestone) *TaskUpdateOne {
	return _u.SetMilestoneID(v.ID)
}

// SetParentID sets the "parent" edge to the Task entity by ID.
func (_u *TaskUpdateOne) SetParentID(id uuid.UUID) *TaskUpdateOne {
	_u.mutation.SetParentID(id)
	return _u
}

// SetNillableParentID sets the "parent" edge to the Task entity by ID if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableParentID(id *uuid.UUID) *TaskUpdateOne {
	if id != nil {
		_u = _u.SetParentID(*id)
	}
	return _u
}

// SetParent sets the "parent" edge to the Task entity.
func (_u *TaskUpdateOne) SetParent(v *Task) *TaskUpdateOne {
	return _u.SetParentID(v.ID)
}

// AddChildIDs adds the "children" edge to the Task entity by IDs.
func (_u *TaskUpdateOne) AddChildIDs(ids ...uuid.UUID) *TaskUpdateOne {
	_u.mutation.AddChildIDs(ids...)
	return _u
}

// AddChildren adds the "children" edges to the Task entity.
func (_u *TaskUpdateOne) AddChildren(v ...*Task) *TaskUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChildIDs(ids...)
}

// AddWorklogIDs adds the "worklogs" edge to the Worklog entity by IDs.
func (_u *TaskUpdateOne) AddWorklogIDs(ids ...uuid.UUID) *TaskUpdateOne {
	_u.mutation.AddWorklogIDs(ids...)
	return _u
}

// AddWorklogs adds the "worklogs" edges to the Worklog entity.
func (_u *TaskUpdateOne) AddWorklogs(v ...*Worklog) *TaskUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddWorklogIDs(ids...)
}

// Mutation returns the TaskMutation object of the builder.
func (_u *TaskUpdateOne) Mutation() *TaskMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *TaskUpdateOne) ClearProject() *TaskUpdateOne {
	_u.mutation.ClearProject()
	return _u
}

// ClearMilestone clears the "milestone" edge to the Milestone entity.
func (_u *TaskUpdateOne) ClearMilestone() *TaskUpdateOne {
	_u.mutation.ClearMilestone()
	return _u
}

// ClearParent clears the "parent" edge to the Task entity.
func (_u *TaskUpdateOne) ClearParent() *TaskUpdateOne {
	_u.mutation.ClearParent()
	return _u
}

// ClearChildren clears all "children" edges to the Task entity.
func (_u *TaskUpdateOne) ClearChildren() *TaskUpdateOne {
	_u.mutation.ClearChildren()
	return _u
}

// RemoveChildIDs removes the "children" edge to Task entities by IDs.
func (_u *TaskUpdateOne) RemoveChildIDs(ids ...uuid.UUID) *TaskUpdateOne {
	_u.mutation.RemoveChildIDs(ids...)
	return _u
}

// RemoveChildren removes "children" edges to Task entities.
func (_u *TaskUpdateOne) RemoveChildren(v ...*Task) *TaskUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChildIDs(ids...)
}

// ClearWorklogs clears all "worklogs" edges to the Worklog entity.
func (_u *TaskUpdateOne) ClearWorklogs() *TaskUpdateOne {
	_u.mutation.ClearWorklogs()
	return _u
}

// RemoveWorklogIDs removes the "worklogs" edge to Worklog entities by IDs.
func (_u *TaskUpdateOne) RemoveWorklogIDs(ids ...uuid.UUID) *TaskUpdateOne {
	_u.mutation.RemoveWorklogIDs(ids...)
	return _u
}

// RemoveWorklogs removes "worklogs" edges to Worklog entities.
func (_u *TaskUpdateOne) RemoveWorklogs(v ...*Worklog) *TaskUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveWorklogIDs(ids...)
}

// Where appends a list predicates to the TaskUpdate builder.
func (_u *TaskUpdateOne) Where(ps ...predicate.Task) *TaskUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TaskUpdateOne) Select(field string, fields ...string) *TaskUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Task entity.
func (_u *TaskUpdateOne) Save(ctx context.Context) (*Task, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TaskUpdateOne) SaveX(ctx context.Context) *Task {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TaskUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TaskUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TaskUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := task.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TaskUpdateOne) check() error {
	if v, ok := _u.mutation.WbsCode(); ok {
		if err := task.WbsCodeValidator(v); err != nil {
			return &ValidationError{Name: "wbs_code", err: fmt.Errorf(`ent: validator failed for field "Task.wbs_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := task.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Task.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := task.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Task.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Priority(); ok {
		if err := task.PriorityValidator(v); err != nil {
			return &ValidationError{Name: "priority", err: fmt.Errorf(`ent: validator failed for field "Task.priority": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Assignee(); ok {
		if err := task.AssigneeValidator(v); err != nil {
			return &ValidationError{Name: "assignee", err: fmt.Errorf(`ent: validator failed for field "Task.assignee": %w`, err)}
		}
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Task.project"`)
	}
	return nil
}

func (_u *TaskUpdateOne) sqlSave(ctx context.Context) (_node *Task, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(task.Table, task.Columns, sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Task.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, task.FieldID)
		for _, f := range fields {
			if !task.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != task.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.WbsCode(); ok {
		_spec.SetField(task.FieldWbsCode, field.TypeString, value)
	}
	if _u.mutation.WbsCodeCleared() {
		_spec.ClearField(task.FieldWbsCode, field.TypeString)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(task.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(task.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(task.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(task.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(task.FieldPriority, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Assignee(); ok {
		_spec.SetField(task.FieldAssignee, field.TypeString, value)
	}
	if _u.mutation.AssigneeCleared() {
		_spec.ClearField(task.FieldAssignee, field.TypeString)
	}
	if value, ok := _u.mutation.EstimatedHours(); ok {
		_spec.SetField(task.FieldEstimatedHours, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedEstimatedHours(); ok {
		_spec.AddField(task.FieldEstimatedHours, field.TypeFloat64, value)
	}
	if _u.mutation.EstimatedHoursCleared() {
		_spec.ClearField(task.FieldEstimatedHours, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ActualHours(); ok {
		_spec.SetField(task.FieldActualHours, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedActualHours(); ok {
		_spec.AddField(task.FieldActualHours, field.TypeFloat64, value)
	}
	if _u.mutation.ActualHoursCleared() {
		_spec.ClearField(task.FieldActualHours, field.TypeFloat64)
	}
	if value, ok := _u.mutation.StartDate(); ok {
		_spec.SetField(task.FieldStartDate, field.TypeTime, value)
	}
	if _u.mutation.StartDateCleared() {
		_spec.ClearField(task.FieldStartDate, field.TypeTime)
	}
	if value, ok := _u.mutation.EndDate(); ok {
		_spec.SetField(task.FieldEndDate, field.TypeTime, value)
	}
	if _u.mutation.EndDateCleared() {
		_spec.ClearField(task.FieldEndDate, field.TypeTime)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(task.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(task.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(task.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.ProjectTable,
			Columns: []string{task.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.ProjectTable,
			Columns: []string{task.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MilestoneCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.MilestoneTable,
			Columns: []string{task.MilestoneColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(milestone.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MilestoneIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.MilestoneTable,
			Columns: []string{task.MilestoneColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(milestone.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.ParentTable,
			Columns: []string{task.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.ParentTable,
			Columns: []string{task.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.ChildrenTable,
			Columns: []string{task.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !_u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.ChildrenTable,
			Columns: []string{task.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.ChildrenTable,
			Columns: []string{task.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.WorklogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.WorklogsTable,
			Columns: []string{task.WorklogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(worklog.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedWorklogsIDs(); len(nodes) > 0 && !_u.mutation.WorklogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.WorklogsTable,
			Columns: []string{task.WorklogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(worklog.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WorklogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.WorklogsTable,
			Columns: []string{task.WorklogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(worklog.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Task{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{task.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
