// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"project-manager/ent/milestone"
	"project-manager/ent/project"
	"project-manager/ent/task"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Task is the model entity for the Task schema.
type Task struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// WbsCode holds the value of the "wbs_code" field.
	WbsCode *string `json:"wbs_code,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description *string `json:"description,omitempty"`
	// Status holds the value of the "status" field.
	Status task.Status `json:"status,omitempty"`
	// Priority holds the value of the "priority" field.
	Priority task.Priority `json:"priority,omitempty"`
	// Assignee holds the value of the "assignee" field.
	Assignee *string `json:"assignee,omitempty"`
	// EstimatedHours holds the value of the "estimated_hours" field.
	EstimatedHours *float64 `json:"estimated_hours,omitempty"`
	// ActualHours holds the value of the "actual_hours" field.
	ActualHours *float64 `json:"actual_hours,omitempty"`
	// StartDate holds the value of the "start_date" field.
	StartDate *time.Time `json:"start_date,omitempty"`
	// EndDate holds the value of the "end_date" field.
	EndDate *time.Time `json:"end_date,omitempty"`
	// SortOrder holds the value of the "sort_order" field.
	SortOrder int `json:"sort_order,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TaskQuery when eager-loading is set.
	Edges           TaskEdges `json:"edges"`
	milestone_tasks *uuid.UUID
	project_tasks   *uuid.UUID
	task_children   *uuid.UUID
	selectValues    sql.SelectValues
}

// TaskEdges holds the relations/edges for other nodes in the graph.
type TaskEdges struct {
	// Project holds the value of the project edge.
	Project *Project `json:"project,omitempty"`
	// Milestone holds the value of the milestone edge.
	Milestone *Milestone `json:"milestone,omitempty"`
	// Parent holds the value of the parent edge.
	Parent *Task `json:"parent,omitempty"`
	// Children holds the value of the children edge.
	Children []*Task `json:"children,omitempty"`
	// Worklogs holds the value of the worklogs edge.
	Worklogs []*Worklog `json:"worklogs,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [5]bool
}

// ProjectOrErr returns the Project value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TaskEdges) ProjectOrErr() (*Project, error) {
	if e.Project != nil {
		return e.Project, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: project.Label}
	}
	return nil, &NotLoadedError{edge: "project"}
}

// MilestoneOrErr returns the Milestone value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TaskEdges) MilestoneOrErr() (*Milestone, error) {
	if e.Milestone != nil {
		return e.Milestone, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: milestone.Label}
	}
	return nil, &NotLoadedError{edge: "milestone"}
}

// ParentOrErr returns the Parent value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TaskEdges) ParentOrErr() (*Task, error) {
	if e.Parent != nil {
		return e.Parent, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: task.Label}
	}
	return nil, &NotLoadedError{edge: "parent"}
}

// ChildrenOrErr returns the Children value or an error if the edge
// was not loaded in eager-loading.
func (e TaskEdges) ChildrenOrErr() ([]*Task, error) {
	if e.loadedTypes[3] {
		return e.Children, nil
	}
	return nil, &NotLoadedError{edge: "children"}
}

// WorklogsOrErr returns the Worklogs value or an error if the edge
// was not loaded in eager-loading.
func (e TaskEdges) WorklogsOrErr() ([]*Worklog, error) {
	if e.loadedTypes[4] {
		return e.Worklogs, nil
	}
	return nil, &NotLoadedError{edge: "worklogs"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Task) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case task.FieldEstimatedHours, task.FieldActualHours:
			values[i] = new(sql.NullFloat64)
		case task.FieldSortOrder:
			values[i] = new(sql.NullInt64)
		case task.FieldWbsCode, task.FieldName, task.FieldDescription, task.FieldStatus, task.FieldPriority, task.FieldAssignee:
			values[i] = new(sql.NullString)
		case task.FieldStartDate, task.FieldEndDate, task.FieldCreatedAt, task.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case task.FieldID:
			values[i] = new(uuid.UUID)
		case task.ForeignKeys[0]: // milestone_tasks
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case task.ForeignKeys[1]: // project_tasks
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case task.ForeignKeys[2]: // task_children
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Task fields.
func (_m *Task) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case task.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case task.FieldWbsCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field wbs_code", values[i])
			} else if value.Valid {
				_m.WbsCode = new(string)
				*_m.WbsCode = value.String
			}
		case task.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case task.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = new(string)
				*_m.Description = value.String
			}
		case task.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = task.Status(value.String)
			}
		case task.FieldPriority:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field priority", values[i])
			} else if value.Valid {
				_m.Priority = task.Priority(value.String)
			}
		case task.FieldAssignee:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field assignee", values[i])
			} else if value.Valid {
				_m.Assignee = new(string)
				*_m.Assignee = value.String
			}
		case task.FieldEstimatedHours:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field estimated_hours", values[i])
			} else if value.Valid {
				_m.EstimatedHours = new(float64)
				*_m.EstimatedHours = value.Float64
			}
		case task.FieldActualHours:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field actual_hours", values[i])
			} else if value.Valid {
				_m.ActualHours = new(float64)
				*_m.ActualHours = value.Float64
			}
		case task.FieldStartDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field start_date", values[i])
			} else if value.Valid {
				_m.StartDate = new(time.Time)
				*_m.StartDate = value.Time
			}
		case task.FieldEndDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field end_date", values[i])
			} else if value.Valid {
				_m.EndDate = new(time.Time)
				*_m.EndDate = value.Time
			}
		case task.FieldSortOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_order", values[i])
			} else if value.Valid {
				_m.SortOrder = int(value.Int64)
			}
		case task.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case task.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case task.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field milestone_tasks", values[i])
			} else if value.Valid {
				_m.milestone_tasks = new(uuid.UUID)
				*_m.milestone_tasks = *value.S.(*uuid.UUID)
			}
		case task.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field project_tasks", values[i])
			} else if value.Valid {
				_m.project_tasks = new(uuid.UUID)
				*_m.project_tasks = *value.S.(*uuid.UUID)
			}
		case task.ForeignKeys[2]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field task_children", values[i])
			} else if value.Valid {
				_m.task_children = new(uuid.UUID)
				*_m.task_children = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Task.
// This includes values selected through modifiers, order, etc.
func (_m *Task) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProject queries the "project" edge of the Task entity.
func (_m *Task) QueryProject() *ProjectQuery {
	return NewTaskClient(_m.config).QueryProject(_m)
}

// QueryMilestone queries the "milestone" edge of the Task entity.
func (_m *Task) QueryMilestone() *MilestoneQuery {
	return NewTaskClient(_m.config).QueryMilestone(_m)
}

// QueryParent queries the "parent" edge of the Task entity.
func (_m *Task) QueryParent() *TaskQuery {
	return NewTaskClient(_m.config).QueryParent(_m)
}

// QueryChildren queries the "children" edge of the Task entity.
func (_m *Task) QueryChildren() *TaskQuery {
	return NewTaskClient(_m.config).QueryChildren(_m)
}

// QueryWorklogs queries the "worklogs" edge of the Task entity.
func (_m *Task) QueryWorklogs() *WorklogQuery {
	return NewTaskClient(_m.config).QueryWorklogs(_m)
}

// Update returns a builder for updating this Task.
// Note that you need to call Task.Unwrap() before calling this method if this Task
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Task) Update() *TaskUpdateOne {
	return NewTaskClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Task entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Task) Unwrap() *Task {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Task is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Task) String() string {
	var builder strings.Builder
	builder.WriteString("Task(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.WbsCode; v != nil {
		builder.WriteString("wbs_code=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	if v := _m.Description; v != nil {
		builder.WriteString("description=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("priority=")
	builder.WriteString(fmt.Sprintf("%v", _m.Priority))
	builder.WriteString(", ")
	if v := _m.Assignee; v != nil {
		builder.WriteString("assignee=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.EstimatedHours; v != nil {
		builder.WriteString("estimated_hours=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ActualHours; v != nil {
		builder.WriteString("actual_hours=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.StartDate; v != nil {
		builder.WriteString("start_date=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.EndDate; v != nil {
		builder.WriteString("end_date=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("sort_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.SortOrder))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Tasks is a parsable slice of Task.
type Tasks []*Task
