// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"project-manager/ent/task"
	"project-manager/ent/worklog"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Worklog is the model entity for the Worklog schema.
type Worklog struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// UserName holds the value of the "user_name" field.
	UserName string `json:"user_name,omitempty"`
	// Hours holds the value of the "hours" field.
	Hours float64 `json:"hours,omitempty"`
	// WorkDate holds the value of the "work_date" field.
	WorkDate time.Time `json:"work_date,omitempty"`
	// Description holds the value of the "description" field.
	Description *string `json:"description,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the WorklogQuery when eager-loading is set.
	Edges         WorklogEdges `json:"edges"`
	task_worklogs *uuid.UUID
	selectValues  sql.SelectValues
}

// WorklogEdges holds the relations/edges for other nodes in the graph.
type WorklogEdges struct {
	// Task holds the value of the task edge.
	Task *Task `json:"task,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TaskOrErr returns the Task value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e WorklogEdges) TaskOrErr() (*Task, error) {
	if e.Task != nil {
		return e.Task, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: task.Label}
	}
	return nil, &NotLoadedError{edge: "task"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Worklog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case worklog.FieldHours:
			values[i] = new(sql.NullFloat64)
		case worklog.FieldUserName, worklog.FieldDescription:
			values[i] = new(sql.NullString)
		case worklog.FieldWorkDate, worklog.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case worklog.FieldID:
			values[i] = new(uuid.UUID)
		case worklog.ForeignKeys[0]: // task_worklogs
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Worklog fields.
func (_m *Worklog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case worklog.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case worklog.FieldUserName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_name", values[i])
			} else if value.Valid {
				_m.UserName = value.String
			}
		case worklog.FieldHours:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field hours", values[i])
			} else if value.Valid {
				_m.Hours = value.Float64
			}
		case worklog.FieldWorkDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field work_date", values[i])
			} else if value.Valid {
				_m.WorkDate = value.Time
			}
		case worklog.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = new(string)
				*_m.Description = value.String
			}
		case worklog.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case worklog.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field task_worklogs", values[i])
			} else if value.Valid {
				_m.task_worklogs = new(uuid.UUID)
				*_m.task_worklogs = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Worklog.
// This includes values selected through modifiers, order, etc.
func (_m *Worklog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTask queries the "task" edge of the Worklog entity.
func (_m *Worklog) QueryTask() *TaskQuery {
	return NewWorklogClient(_m.config).QueryTask(_m)
}

// Update returns a builder for updating this Worklog.
// Note that you need to call Worklog.Unwrap() before calling this method if this Worklog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Worklog) Update() *WorklogUpdateOne {
	return NewWorklogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Worklog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Worklog) Unwrap() *Worklog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Worklog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Worklog) String() string {
	var builder strings.Builder
	builder.WriteString("Worklog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_name=")
	builder.WriteString(_m.UserName)
	builder.WriteString(", ")
	builder.WriteString("hours=")
	builder.WriteString(fmt.Sprintf("%v", _m.Hours))
	builder.WriteString(", ")
	builder.WriteString("work_date=")
	builder.WriteString(_m.WorkDate.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.Description; v != nil {
		builder.WriteString("description=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Worklogs is a parsable slice of Worklog.
type Worklogs []*Worklog
