// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"project-manager/ent/task"
	"project-manager/ent/worklog"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// WorklogCreate is the builder for creating a Worklog entity.
type WorklogCreate struct {
	config
	mutation *WorklogMutation
	hooks    []Hook
}

// SetUserName sets the "user_name" field.
func (_c *WorklogCreate) SetUserName(v string) *WorklogCreate {
	_c.mutation.SetUserName(v)
	return _c
}

// SetHours sets the "hours" field.
func (_c *WorklogCreate) SetHours(v float64) *WorklogCreate {
	_c.mutation.SetHours(v)
	return _c
}

// SetWorkDate sets the "work_date" field.
func (_c *WorklogCreate) SetWorkDate(v time.Time) *WorklogCreate {
	_c.mutation.SetWorkDate(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *WorklogCreate) SetDescription(v string) *WorklogCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *WorklogCreate) SetNillableDescription(v *string) *WorklogCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *WorklogCreate) SetCreatedAt(v time.Time) *WorklogCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *WorklogCreate) SetNillableCreatedAt(v *time.Time) *WorklogCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *WorklogCreate) SetID(v uuid.UUID) *WorklogCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *WorklogCreate) SetNillableID(v *uuid.UUID) *WorklogCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetTaskID sets the "task" edge to the Task entity by ID.
func (_c *WorklogCreate) SetTaskID(id uuid.UUID) *WorklogCreate {
	_c.mutation.SetTaskID(id)
	return _c
}

// SetTask sets the "task" edge to the Task entity.
func (_c *WorklogCreate) SetTask(v *Task) *WorklogCreate {
	return _c.SetTaskID(v.ID)
}

// Mutation returns the WorklogMutation object of the builder.
func (_c *WorklogCreate) Mutation() *WorklogMutation {
	return _c.mutation
}

// Save creates the Worklog in the database.
func (_c *WorklogCreate) Save(ctx context.Context) (*Worklog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *WorklogCreate) SaveX(ctx context.Context) *Worklog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WorklogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WorklogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *WorklogCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := worklog.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := worklog.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *WorklogCreate) check() error {
	if _, ok := _c.mutation.UserName(); !ok {
		return &ValidationError{Name: "user_name", err: errors.New(`ent: missing required field "Worklog.user_name"`)}
	}
	if v, ok := _c.mutation.UserName(); ok {
		if err := worklog.UserNameValidator(v); err != nil {
			return &ValidationError{Name: "user_name", err: fmt.Errorf(`ent: validator failed for field "Worklog.user_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Hours(); !ok {
		return &ValidationError{Name: "hours", err: errors.New(`ent: missing required field "Worklog.hours"`)}
	}
	if _, ok := _c.mutation.WorkDate(); !ok {
		return &ValidationError{Name: "work_date", err: errors.New(`ent: missing required field "Worklog.work_date"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Worklog.created_at"`)}
	}
	if len(_c.mutation.TaskIDs()) == 0 {
		return &ValidationError{Name: "task", err: errors.New(`ent: missing required edge "Worklog.task"`)}
	}
	return nil
}

func (_c *WorklogCreate) sqlSave(ctx context.Context) (*Worklog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *WorklogCreate) createSpec() (*Worklog, *sqlgraph.CreateSpec) {
	var (
		_node = &Worklog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(worklog.Table, sqlgraph.NewFieldSpec(worklog.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.UserName(); ok {
		_spec.SetField(worklog.FieldUserName, field.TypeString, value)
		_node.UserName = value
	}
	if value, ok := _c.mutation.Hours(); ok {
		_spec.SetField(worklog.FieldHours, field.TypeFloat64, value)
		_node.Hours = value
	}
	if value, ok := _c.mutation.WorkDate(); ok {
		_spec.SetField(worklog.FieldWorkDate, field.TypeTime, value)
		_node.WorkDate = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(worklog.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(worklog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   worklog.TaskTable,
			Columns: []string{worklog.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.task_worklogs = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// WorklogCreateBulk is the builder for creating many Worklog entities in bulk.
type WorklogCreateBulk struct {
	config
	err      error
	builders []*WorklogCreate
}

// Save creates the Worklog entities in the database.
func (_c *WorklogCreateBulk) Save(ctx context.Context) ([]*Worklog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Worklog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WorklogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *WorklogCreateBulk) SaveX(ctx context.Context) []*Worklog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WorklogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WorklogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
