// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"project-manager/ent/predicate"
	"project-manager/ent/task"
	"project-manager/ent/worklog"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// WorklogUpdate is the builder for updating Worklog entities.
type WorklogUpdate struct {
	config
	hooks    []Hook
	mutation *WorklogMutation
}

// Where appends a list predicates to the WorklogUpdate builder.
func (_u *WorklogUpdate) Where(ps ...predicate.Worklog) *WorklogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserName sets the "user_name" field.
func (_u *WorklogUpdate) SetUserName(v string) *WorklogUpdate {
	_u.mutation.SetUserName(v)
	return _u
}

// SetNillableUserName sets the "user_name" field if the given value is not nil.
func (_u *WorklogUpdate) SetNillableUserName(v *string) *WorklogUpdate {
	if v != nil {
		_u.SetUserName(*v)
	}
	return _u
}

// SetHours sets the "hours" field.
func (_u *WorklogUpdate) SetHours(v float64) *WorklogUpdate {
	_u.mutation.ResetHours()
	_u.mutation.SetHours(v)
	return _u
}

// SetNillableHours sets the "hours" field if the given value is not nil.
func (_u *WorklogUpdate) SetNillableHours(v *float64) *WorklogUpdate {
	if v != nil {
		_u.SetHours(*v)
	}
	return _u
}

// AddHours adds value to the "hours" field.
func (_u *WorklogUpdate) AddHours(v float64) *WorklogUpdate {
	_u.mutation.AddHours(v)
	return _u
}

// SetWorkDate sets the "work_date" field.
func (_u *WorklogUpdate) SetWorkDate(v time.Time) *WorklogUpdate {
	_u.mutation.SetWorkDate(v)
	return _u
}

// SetNillableWorkDate sets the "work_date" field if the given value is not nil.
func (_u *WorklogUpdate) SetNillableWorkDate(v *time.Time) *WorklogUpdate {
	if v != nil {
		_u.SetWorkDate(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *WorklogUpdate) SetDescription(v string) *WorklogUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *WorklogUpdate) SetNillableDescription(v *string) *WorklogUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *WorklogUpdate) ClearDescription() *WorklogUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetTaskID sets the "task" edge to the Task entity by ID.
func (_u *WorklogUpdate) SetTaskID(id uuid.UUID) *WorklogUpdate {
	_u.mutation.SetTaskID(id)
	return _u
}

// SetTask sets the "task" edge to the Task entity.
func (_u *WorklogUpdate) SetTask(v *Task) *WorklogUpdate {
	return _u.SetTaskID(v.ID)
}

// Mutation returns the WorklogMutation object of the builder.
func (_u *WorklogUpdate) Mutation() *WorklogMutation {
	return _u.mutation
}

// ClearTask clears the "task" edge to the Task entity.
func (_u *WorklogUpdate) ClearTask() *WorklogUpdate {
	_u.mutation.ClearTask()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WorklogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorklogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WorklogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorklogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WorklogUpdate) check() error {
	if v, ok := _u.mutation.UserName(); ok {
		if err := worklog.UserNameValidator(v); err != nil {
			return &ValidationError{Name: "user_name", err: fmt.Errorf(`ent: validator failed for field "Worklog.user_name": %w`, err)}
		}
	}
	if _u.mutation.TaskCleared() && len(_u.mutation.TaskIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Worklog.task"`)
	}
	return nil
}

func (_u *WorklogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(worklog.Table, worklog.Columns, sqlgraph.NewFieldSpec(worklog.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserName(); ok {
		_spec.SetField(worklog.FieldUserName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Hours(); ok {
		_spec.SetField(worklog.FieldHours, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedHours(); ok {
		_spec.AddField(worklog.FieldHours, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.WorkDate(); ok {
		_spec.SetField(worklog.FieldWorkDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(worklog.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(worklog.FieldDescription, field.TypeString)
	}
	if _u.mutation.TaskCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   worklog.TaskTable,
			Columns: []string{worklog.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   worklog.TaskTable,
			Columns: []string{worklog.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{worklog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WorklogUpdateOne is the builder for updating a single Worklog entity.
type WorklogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WorklogMutation
}

// SetUserName sets the "user_name" field.
func (_u *WorklogUpdateOne) SetUserName(v string) *WorklogUpdateOne {
	_u.mutation.SetUserName(v)
	return _u
}

// SetNillableUserName sets the "user_name" field if the given value is not nil.
func (_u *WorklogUpdateOne) SetNillableUserName(v *string) *WorklogUpdateOne {
	if v != nil {
		_u.SetUserName(*v)
	}
	return _u
}

// SetHours sets the "hours" field.
func (_u *WorklogUpdateOne) SetHours(v float64) *WorklogUpdateOne {
	_u.mutation.ResetHours()
	_u.mutation.SetHours(v)
	return _u
}

// SetNillableHours sets the "hours" field if the given value is not nil.
func (_u *WorklogUpdateOne) SetNillableHours(v *float64) *WorklogUpdateOne {
	if v != nil {
		_u.SetHours(*v)
	}
	return _u
}

// AddHours adds value to the "hours" field.
func (_u *WorklogUpdateOne) AddHours(v float64) *WorklogUpdateOne {
	_u.mutation.AddHours(v)
	return _u
}

// SetWorkDate sets the "work_date" field.
func (_u *WorklogUpdateOne) SetWorkDate(v time.Time) *WorklogUpdateOne {
	_u.mutation.SetWorkDate(v)
	return _u
}

// SetNillableWorkDate sets the "work_date" field if the given value is not nil.
func (_u *WorklogUpdateOne) SetNillableWorkDate(v *time.Time) *WorklogUpdateOne {
	if v != nil {
		_u.SetWorkDate(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *WorklogUpdateOne) SetDescription(v string) *WorklogUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *WorklogUpdateOne) SetNillableDescription(v *string) *WorklogUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *WorklogUpdateOne) ClearDescription() *WorklogUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetTaskID sets the "task" edge to the Task entity by ID.
func (_u *WorklogUpdateOne) SetTaskID(id uuid.UUID) *WorklogUpdateOne {
	_u.mutation.SetTaskID(id)
	return _u
}

// SetTask sets the "task" edge to the Task entity.
func (_u *WorklogUpdateOne) SetTask(v *Task) *WorklogUpdateOne {
	return _u.SetTaskID(v.ID)
}

// Mutation returns the WorklogMutation object of the builder.
func (_u *WorklogUpdateOne) Mutation() *WorklogMutation {
	return _u.mutation
}

// ClearTask clears the "task" edge to the Task entity.
func (_u *WorklogUpdateOne) ClearTask() *WorklogUpdateOne {
	_u.mutation.ClearTask()
	return _u
}

// Where appends a list predicates to the WorklogUpdate builder.
func (_u *WorklogUpdateOne) Where(ps ...predicate.Worklog) *WorklogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WorklogUpdateOne) Select(field string, fields ...string) *WorklogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Worklog entity.
func (_u *WorklogUpdateOne) Save(ctx context.Context) (*Worklog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorklogUpdateOne) SaveX(ctx context.Context) *Worklog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WorklogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorklogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WorklogUpdateOne) check() error {
	if v, ok := _u.mutation.UserName(); ok {
		if err := worklog.UserNameValidator(v); err != nil {
			return &ValidationError{Name: "user_name", err: fmt.Errorf(`ent: validator failed for field "Worklog.user_name": %w`, err)}
		}
	}
	if _u.mutation.TaskCleared() && len(_u.mutation.TaskIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Worklog.task"`)
	}
	return nil
}

func (_u *WorklogUpdateOne) sqlSave(ctx context.Context) (_node *Worklog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(worklog.Table, worklog.Columns, sqlgraph.NewFieldSpec(worklog.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Worklog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, worklog.FieldID)
		for _, f := range fields {
			if !worklog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != worklog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserName(); ok {
		_spec.SetField(worklog.FieldUserName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Hours(); ok {
		_spec.SetField(worklog.FieldHours, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedHours(); ok {
		_spec.AddField(worklog.FieldHours, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.WorkDate(); ok {
		_spec.SetField(worklog.FieldWorkDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(worklog.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(worklog.FieldDescription, field.TypeString)
	}
	if _u.mutation.TaskCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   worklog.TaskTable,
			Columns: []string{worklog.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   worklog.TaskTable,
			Columns: []string{worklog.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Worklog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{worklog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
