// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// MilestonesColumns holds the columns for the "milestones" table.
	MilestonesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString, Size: 255},
		{Name: "due_date", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "date"}},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"pending", "completed"}, Default: "pending"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "project_milestones", Type: field.TypeUUID},
	}
	// MilestonesTable holds the schema information for the "milestones" table.
	MilestonesTable = &schema.Table{
		Name:       "milestones",
		Columns:    MilestonesColumns,
		PrimaryKey: []*schema.Column{MilestonesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "milestones_projects_milestones",
				Columns:    []*schema.Column{MilestonesColumns[6]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// ProjectsColumns holds the columns for the "projects" table.
	ProjectsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString, Size: 255},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"planning", "in_progress", "completed", "on_hold"}, Default: "planning"},
		{Name: "start_date", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "date"}},
		{Name: "end_date", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "date"}},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// ProjectsTable holds the schema information for the "projects" table.
	ProjectsTable = &schema.Table{
		Name:       "projects",
		Columns:    ProjectsColumns,
		PrimaryKey: []*schema.Column{ProjectsColumns[0]},
	}
	// TasksColumns holds the columns for the "tasks" table.
	TasksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "wbs_code", Type: field.TypeString, Nullable: true, Size: 50},
		{Name: "name", Type: field.TypeString, Size: 255},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"not_started", "in_progress", "completed", "blocked"}, Default: "not_started"},
		{Name: "priority", Type: field.TypeEnum, Enums: []string{"low", "medium", "high"}, Default: "medium"},
		{Name: "assignee", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "estimated_hours", Type: field.TypeFloat64, Nullable: true},
		{Name: "actual_hours", Type: field.TypeFloat64, Nullable: true},
		{Name: "start_date", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "date"}},
		{Name: "end_date", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "date"}},
		{Name: "sort_order", Type: field.TypeInt, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "milestone_tasks", Type: field.TypeUUID, Nullable: true},
		{Name: "project_tasks", Type: field.TypeUUID},
		{Name: "task_children", Type: field.TypeUUID, Nullable: true},
	}
	// TasksTable holds the schema information for the "tasks" table.
	TasksTable = &schema.Table{
		Name:       "tasks",
		Columns:    TasksColumns,
		PrimaryKey: []*schema.Column{TasksColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tasks_milestones_tasks",
				Columns:    []*schema.Column{TasksColumns[14]},
				RefColumns: []*schema.Column{MilestonesColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "tasks_projects_tasks",
				Columns:    []*schema.Column{TasksColumns[15]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "tasks_tasks_children",
				Columns:    []*schema.Column{TasksColumns[16]},
				RefColumns: []*schema.Column{TasksColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// WorklogsColumns holds the columns for the "worklogs" table.
	WorklogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "user_name", Type: field.TypeString, Size: 255},
		{Name: "hours", Type: field.TypeFloat64},
		{Name: "work_date", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "date"}},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "task_worklogs", Type: field.TypeUUID},
	}
	// WorklogsTable holds the schema information for the "worklogs" table.
	WorklogsTable = &schema.Table{
		Name:       "worklogs",
		Columns:    WorklogsColumns,
		PrimaryKey: []*schema.Column{WorklogsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "worklogs_tasks_worklogs",
				Columns:    []*schema.Column{WorklogsColumns[6]},
				RefColumns: []*schema.Column{TasksColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		MilestonesTable,
		ProjectsTable,
		TasksTable,
		WorklogsTable,
	}
)

func init() {
	MilestonesTable.ForeignKeys[0].RefTable = ProjectsTable
	TasksTable.ForeignKeys[0].RefTable = MilestonesTable
	TasksTable.ForeignKeys[1].RefTable = ProjectsTable
	TasksTable.ForeignKeys[2].RefTable = TasksTable
	WorklogsTable.ForeignKeys[0].RefTable = TasksTable
}
